apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.objectName }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.objectName }}
  template:
    metadata:
      name: {{ .Values.objectName }}
      labels:
        app: {{ .Values.objectName }} 
    spec:
      containers:
      - name: {{ .Values.objectName }}
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: {{ .Values.containerPort }}
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests: 
            memory: 500M
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources