{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  name: {{ .Values.objectName }}-ingress
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.objectName }}-service
            port: 
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
{{- end }}
