objectName: prometheus
replicaCount: 1
ImageName: prom/prometheus
containerPort: 9090
service:
  type: ClusterIP
  port: 80

ingress: 
  enabled: true
  hostname: testmetrics.un1xman.local
  annotations:
    kubernetes.io/ingress.class: "nginx"
  

pvc:
  name: prometheus
  accessMode: ReadWriteOnce
  storageSize: "5Gi"
  storageclassname: glusterfs-heketi
